### ISSUE TITLE
[Feature] Implement failure-tolerant etcd restoration

### ISSUE THREAD

**Issue by shreyas-s-rao** [gardener/etcd-steward#11]
**How to categorize this issue?**

/kind enhancement

**What would you like to be added**:
Steward should implement etcd restoration from snapshots with maximum re-use from upstream etcd's APIs such as `Restore`, rather than implementing `MakeDB` and `MakeWALAndSnap` within steward, and must also be tolerant to failures arising from restart of steward or database storage space exceeding the configured quota.

Restoration involves restoring (downloading) a full snapshot, and then applying delta snapshots sequentially on an [embedded] etcd started from the full snapshot. If restoration fails midway, the process exits, and is restarted by Kubernetes, upon which restoration is re-attempted all over from scratch. This makes restoration a very heavy operation, and must be made more failure-tolerant so that it can "continue" from where it previously left off. Essentially, restoration should support restoration of etcd revisions from where it had previously left off, so that it is not limited to restoring the entire etcd in one single run. A further optimisation to this is to download and save the snapshot files locally before applying them; if steward restarts halfway between applying a particular snapshot, once it comes back up it need not re-download the snapshot file, but rather re-use the already downloaded file to apply the remaining revisions from that snapshot. 

Furthermore, restoration should not hard-code starting of an embedded etcd within steward for applying delta snapshots, but should rather provide a callback to trigger the starting of an etcd from anywhere. This can be used by steward to call an API on etcd-wrapper to start the embedded etcd within the etcd-wrapper process, and steward can create a client for this etcd and use it for applying delta snapshots. This allows steward to use minimal memory, by avoiding running a full-fledged embedded etcd within itself. 

Additionally, restoration should also support running defragmentation during the process of applying delta snapshots, to ensure that the DB size of the etcd being restored is kept in check throughout restoration. Defragmentation can either be triggered by the growing DB size (preferable, and can be re-used from #5 ), or can be run after applying every X delta snapshots or Y etcd revisions.

**Why is this needed**:
Part of #1 

**Task List:**
- [ ] Restoration of etcd DB from snapshots, with support for partial restoration of etcd revisions
- [ ] Provide callback for restorer to start embedded etcd elsewhere, to be used for applying delta snapshots
- [ ] Run defragmentation during restoration to keep DB size in check

#### Dependencies

Depends on: https://github.com/gardener/etcd-steward/issues/2, https://github.com/gardener/etcd-steward/issues/7, https://github.com/gardener/etcd-steward/issues/8
