### ISSUE TITLE
[Feature] Implement lean and well-defined snapstore for object storage providers

### ISSUE THREAD

**Issue by shreyas-s-rao** [gardener/etcd-steward#7]
**How to categorize this issue?**

/kind enhancement

**What would you like to be added**:
Steward should provide a lean snapstore, with well-defined interfaces and APIs for snapstore operations for each object storage provider. Possible APIs for the snapstore object can be `Upload`, `Download`, `GetInfo`, `List`, `Delete`, with scope to further create a `CompressedSnapstore` that implements the `Snapstore` interface and provides compression/decompression functionality within existing `Upload` and `Download` methods respectively.

**Why is this needed**:
Part of #1 

**Task List**
- [ ] Interface
- [ ] Local provider
- [ ] AWS S3 provider
- [ ] Azure ABS provider
- [ ] GCP GCS provider
- [ ] Openstack Swift provider
- [ ] Alicloud OSS provider
- [ ] Dell EMC ECS provider
- [ ] Openshift OCS provider
