### ISSUE TITLE
[Feature] Implement snapshot compression/decompression

### ISSUE THREAD

**Issue by shreyas-s-rao** [gardener/etcd-steward#8]
**How to categorize this issue?**

/kind enhancement

**What would you like to be added**:
Steward should provide support for compressing and decompressing snapshots to be uploaded/downloaded, to ensure least usage of object storage space for storing etcd snapshots. As part of this story, steward must also implement a `CompressedSnapstore` which provides snapshot compression and decompression for `Upload` and `Download` methods of the Snapstore interface defined by #7 .

Etcd-backup-restore currently supports 3 compression algorithms, namely [`gzip`](https://en.wikipedia.org/wiki/Gzip), [`lzw`](https://en.wikipedia.org/wiki/Lempel%E2%80%93Ziv%E2%80%93Welch) and [`zlib`](https://www.zlib.net/).

**Why is this needed**:
Part of #1 

**Task List:**
- [ ] Evaluate [`snappy`](https://github.com/google/snappy) and [`lz4`](https://github.com/lz4/lz4) compression algorithms as possible (better) alternatives
- [ ] Measure size reduction vs time vs CPU usage for all compression algorithms, and determine best suited algorithm for etcd snapshots in Kubernetes context. Also decide whether compression must be enabled by default or not
- [ ] Implement compression and decompression for selected algorithms
- [ ] Implement `CompressedSnapstore` for the selected algorithms

#### Dependencies

Depends on: https://github.com/gardener/etcd-steward/issues/7
